# Generated by Django 4.2 on 2023-06-11 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventsapp', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='is_confirmed',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
