# Generated by Django 4.2 on 2023-06-10 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customusers',
            managers=[
            ],
        ),
    ]
